// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUdYV-nMUs_1_eAr1A4nH3JV0cSWHi5c',
    appId: '1:871371757318:web:250189f231b1101e45f087',
    messagingSenderId: '871371757318',
    projectId: 'flutter-firebase-demo-27d5d',
    authDomain: 'flutter-firebase-demo-27d5d.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-demo-27d5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-demo-27d5d.appspot.com',
    measurementId: 'G-R5SV0Q7FC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKyuA7tCZY02_JWWlKisyZAThRxEBxgN8',
    appId: '1:871371757318:android:155eab429889e8af45f087',
    messagingSenderId: '871371757318',
    projectId: 'flutter-firebase-demo-27d5d',
    databaseURL: 'https://flutter-firebase-demo-27d5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-demo-27d5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4jw3Hvz31JehHu6Mg21tEIntM00yHWKg',
    appId: '1:871371757318:ios:e356ae1a4db1b88045f087',
    messagingSenderId: '871371757318',
    projectId: 'flutter-firebase-demo-27d5d',
    databaseURL: 'https://flutter-firebase-demo-27d5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-demo-27d5d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4jw3Hvz31JehHu6Mg21tEIntM00yHWKg',
    appId: '1:871371757318:ios:e437922eeb87085345f087',
    messagingSenderId: '871371757318',
    projectId: 'flutter-firebase-demo-27d5d',
    databaseURL: 'https://flutter-firebase-demo-27d5d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-demo-27d5d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
